/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as HowToBuildAWorldRouteImport } from './routes/how-to-build-a-world'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideHowToMakeAConceptAlbumRouteImport } from './routes/guide.how-to-make-a-concept-album'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToBuildAWorldRoute = HowToBuildAWorldRouteImport.update({
  id: '/how-to-build-a-world',
  path: '/how-to-build-a-world',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideHowToMakeAConceptAlbumRoute =
  GuideHowToMakeAConceptAlbumRouteImport.update({
    id: '/guide/how-to-make-a-concept-album',
    path: '/guide/how-to-make-a-concept-album',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/how-to-build-a-world': typeof HowToBuildAWorldRoute
  '/listen': typeof ListenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/how-to-make-a-concept-album': typeof GuideHowToMakeAConceptAlbumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/how-to-build-a-world': typeof HowToBuildAWorldRoute
  '/listen': typeof ListenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/how-to-make-a-concept-album': typeof GuideHowToMakeAConceptAlbumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/how-to-build-a-world': typeof HowToBuildAWorldRoute
  '/listen': typeof ListenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/how-to-make-a-concept-album': typeof GuideHowToMakeAConceptAlbumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/how-to-build-a-world'
    | '/listen'
    | '/sitemap.xml'
    | '/guide/how-to-make-a-concept-album'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/how-to-build-a-world'
    | '/listen'
    | '/sitemap.xml'
    | '/guide/how-to-make-a-concept-album'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/how-to-build-a-world'
    | '/listen'
    | '/sitemap.xml'
    | '/guide/how-to-make-a-concept-album'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  HowToBuildAWorldRoute: typeof HowToBuildAWorldRoute
  ListenRoute: typeof ListenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuideHowToMakeAConceptAlbumRoute: typeof GuideHowToMakeAConceptAlbumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-build-a-world': {
      id: '/how-to-build-a-world'
      path: '/how-to-build-a-world'
      fullPath: '/how-to-build-a-world'
      preLoaderRoute: typeof HowToBuildAWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/how-to-make-a-concept-album': {
      id: '/guide/how-to-make-a-concept-album'
      path: '/guide/how-to-make-a-concept-album'
      fullPath: '/guide/how-to-make-a-concept-album'
      preLoaderRoute: typeof GuideHowToMakeAConceptAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  HowToBuildAWorldRoute: HowToBuildAWorldRoute,
  ListenRoute: ListenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuideHowToMakeAConceptAlbumRoute: GuideHowToMakeAConceptAlbumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
