/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlbumRouteImport } from './routes/album'

const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/album': typeof AlbumRoute
}
export interface FileRoutesByTo {
  '/album': typeof AlbumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/album': typeof AlbumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/album'
  fileRoutesByTo: FileRoutesByTo
  to: '/album'
  id: '__root__' | '/album'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AlbumRoute: typeof AlbumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AlbumRoute: AlbumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
